import { defineConfig } from "tinacms";

const branch =
  process.env.NEXT_PUBLIC_TINA_BRANCH ||
  process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_REF ||
  process.env.HEAD ||
  "main";

const singletonUi = (route: string) => ({
  allowedActions: {
    create: false,
    delete: false,
  },
  router: () => route,
});

const iconOptions = [
  { label: "Navigazione", value: "navigation" },
  { label: "Bagagli", value: "luggage" },
  { label: "Assistenza tecnica", value: "wrench" },
  { label: "GPS / satellite", value: "satellite" },
  { label: "Alloggio", value: "home" },
  { label: "Regalo", value: "gift" },
  { label: "Percorso", value: "route" },
  { label: "Moto / bici", value: "bike" },
  { label: "Storia", value: "castle" },
  { label: "Bosco", value: "trees" },
  { label: "Montagna", value: "mountain" },
  { label: "Mare", value: "waves" },
  { label: "Borgo", value: "building" },
  { label: "Cibo", value: "food" },
];

export default defineConfig({
  branch,
  clientId: process.env.NEXT_PUBLIC_TINA_CLIENT_ID,
  token: process.env.TINA_TOKEN,
  build: {
    outputFolder: "admin",
    publicFolder: "public",
  },
  media: {
    tina: {
      mediaRoot: "media/cms",
      publicFolder: "public",
    },
  },
  schema: {
    collections: [
      {
        name: "homepage",
        label: "Homepage",
        path: "content/homepage",
        format: "json",
        match: { include: "index" },
        ui: singletonUi("/"),
        fields: [
          {
            type: "object",
            name: "hero",
            label: "Apertura",
            fields: [
              { type: "string", name: "location", label: "Sopratitolo", required: true },
              { type: "string", name: "title", label: "Titolo", required: true },
              { type: "string", name: "accent", label: "Titolo evidenziato", required: true },
              {
                type: "string",
                name: "description",
                label: "Descrizione",
                ui: { component: "textarea" },
                required: true,
              },
              { type: "image", name: "logo", label: "Logo / immagine principale" },
              { type: "string", name: "logoAlt", label: "Testo alternativo immagine" },
            ],
          },
          {
            type: "object",
            name: "experiences",
            label: "Sezione esperienze",
            fields: [
              { type: "string", name: "eyebrow", label: "Sopratitolo" },
              { type: "string", name: "title", label: "Titolo" },
              { type: "string", name: "accent", label: "Titolo evidenziato" },
              { type: "string", name: "intro", label: "Introduzione", ui: { component: "textarea" } },
            ],
          },
          {
            type: "object",
            name: "featuredTours",
            label: "Tour in evidenza",
            fields: [
              { type: "string", name: "eyebrow", label: "Sopratitolo" },
              { type: "string", name: "title", label: "Titolo" },
              { type: "string", name: "accent", label: "Titolo evidenziato" },
              { type: "string", name: "intro", label: "Introduzione", ui: { component: "textarea" } },
              {
                type: "string",
                name: "tourNames",
                label: "Nomi dei tour mostrati",
                list: true,
              },
            ],
          },
          {
            type: "object",
            name: "journey",
            label: "Cosa vivrai",
            fields: [
              { type: "string", name: "eyebrow", label: "Sopratitolo" },
              { type: "string", name: "title", label: "Titolo" },
              { type: "string", name: "accent", label: "Titolo evidenziato" },
              { type: "string", name: "intro", label: "Introduzione", ui: { component: "textarea" } },
              {
                type: "object",
                name: "items",
                label: "Esperienze",
                list: true,
                ui: { itemProps: (item) => ({ label: item?.label || "Esperienza" }) },
                fields: [
                  {
                    type: "string",
                    name: "icon",
                    label: "Icona",
                    options: iconOptions,
                    required: true,
                  },
                  { type: "string", name: "label", label: "Titolo", required: true },
                  {
                    type: "string",
                    name: "description",
                    label: "Descrizione",
                    ui: { component: "textarea" },
                    required: true,
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "guides",
            label: "Guide",
            fields: [
              { type: "string", name: "eyebrow", label: "Sopratitolo" },
              { type: "string", name: "title", label: "Titolo" },
              { type: "string", name: "accent", label: "Titolo evidenziato" },
              {
                type: "object",
                name: "items",
                label: "Persone",
                list: true,
                ui: { itemProps: (item) => ({ label: item?.name || "Guida" }) },
                fields: [
                  { type: "string", name: "name", label: "Nome", required: true },
                  { type: "string", name: "role", label: "Ruolo", required: true },
                  {
                    type: "string",
                    name: "description",
                    label: "Descrizione",
                    ui: { component: "textarea" },
                    required: true,
                  },
                  { type: "image", name: "image", label: "Foto" },
                  { type: "string", name: "imageAlt", label: "Testo alternativo foto" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "about",
            label: "Chi siamo",
            fields: [
              { type: "string", name: "eyebrow", label: "Sopratitolo" },
              { type: "string", name: "titleLine1", label: "Titolo — riga 1" },
              { type: "string", name: "titleLine2", label: "Titolo — riga 2" },
              { type: "string", name: "titleAccent", label: "Titolo evidenziato" },
              {
                type: "string",
                name: "paragraphs",
                label: "Paragrafi",
                list: true,
                ui: { component: "textarea" },
              },
              { type: "string", name: "quote", label: "Frase in evidenza", ui: { component: "textarea" } },
              { type: "image", name: "image", label: "Foto" },
              { type: "string", name: "imageAlt", label: "Testo alternativo foto" },
              { type: "string", name: "badgeValue", label: "Valore riquadro" },
              { type: "string", name: "badgeText", label: "Testo riquadro", ui: { component: "textarea" } },
            ],
          },
          {
            type: "object",
            name: "gallery",
            label: "Galleria",
            fields: [
              { type: "string", name: "eyebrow", label: "Sopratitolo" },
              { type: "string", name: "title", label: "Titolo" },
              { type: "string", name: "accent", label: "Titolo evidenziato" },
              { type: "string", name: "intro", label: "Introduzione", ui: { component: "textarea" } },
              {
                type: "object",
                name: "images",
                label: "Immagini",
                list: true,
                ui: { itemProps: (item) => ({ label: item?.alt || "Immagine" }) },
                fields: [
                  { type: "image", name: "image", label: "File", required: true },
                  { type: "string", name: "alt", label: "Testo alternativo", required: true },
                  {
                    type: "string",
                    name: "layout",
                    label: "Dimensione",
                    options: [
                      { label: "Normale", value: "normal" },
                      { label: "Larga", value: "wide" },
                      { label: "Grande", value: "featured" },
                    ],
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "included",
            label: "Servizi inclusi",
            fields: [
              { type: "string", name: "title", label: "Titolo" },
              { type: "string", name: "accent", label: "Titolo evidenziato" },
              { type: "string", name: "intro", label: "Introduzione", ui: { component: "textarea" } },
              {
                type: "object",
                name: "items",
                label: "Servizi",
                list: true,
                ui: { itemProps: (item) => ({ label: item?.label || "Servizio" }) },
                fields: [
                  {
                    type: "string",
                    name: "icon",
                    label: "Icona",
                    options: iconOptions,
                    required: true,
                  },
                  { type: "string", name: "label", label: "Nome del servizio", required: true },
                ],
              },
              { type: "string", name: "note", label: "Nota", ui: { component: "textarea" } },
            ],
          },
          {
            type: "object",
            name: "faq",
            label: "FAQ",
            fields: [
              { type: "string", name: "eyebrow", label: "Sopratitolo" },
              { type: "string", name: "title", label: "Titolo" },
              {
                type: "object",
                name: "items",
                label: "Domande",
                list: true,
                ui: { itemProps: (item) => ({ label: item?.question || "Domanda" }) },
                fields: [
                  { type: "string", name: "question", label: "Domanda", required: true },
                  {
                    type: "string",
                    name: "answer",
                    label: "Risposta",
                    ui: { component: "textarea" },
                    required: true,
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "contact",
            label: "Sezione contatti",
            fields: [
              { type: "string", name: "eyebrow", label: "Sopratitolo" },
              { type: "string", name: "title", label: "Titolo" },
              { type: "string", name: "accent", label: "Titolo evidenziato" },
              { type: "string", name: "intro", label: "Introduzione", ui: { component: "textarea" } },
            ],
          },
        ],
      },
      {
        name: "tourCatalog",
        label: "Tour, date e prezzi",
        path: "content/tours",
        format: "json",
        match: { include: "index" },
        ui: singletonUi("/itinerari"),
        fields: [
          {
            type: "object",
            name: "tours",
            label: "Tour",
            list: true,
            ui: { itemProps: (item) => ({ label: item?.name || "Tour" }) },
            fields: [
              { type: "string", name: "name", label: "Nome", required: true, isTitle: true },
              {
                type: "string",
                name: "type",
                label: "Tipo",
                options: ["Maxienduro", "Enduro", "Quad", "4x4", "E-Bike", "Su Misura"],
                required: true,
              },
              { type: "string", name: "duration", label: "Durata", required: true },
              { type: "string", name: "distance", label: "Distanza", required: true },
              { type: "string", name: "level", label: "Livello", required: true },
              { type: "string", name: "offroad", label: "Percentuale sterrato", required: true },
              { type: "string", name: "interest", label: "Punti di interesse", required: true },
              { type: "boolean", name: "lunchIncluded", label: "Pranzo incluso" },
              { type: "string", name: "period", label: "Periodo consigliato", required: true },
              { type: "datetime", name: "date", label: "Data della prossima partenza" },
              { type: "string", name: "price", label: "Prezzo", required: true },
              {
                type: "string",
                name: "description",
                label: "Descrizione",
                ui: { component: "textarea" },
                required: true,
              },
              {
                type: "string",
                name: "groups",
                label: "Formato",
                list: true,
                options: [
                  { label: "Weekend", value: "weekend" },
                  { label: "Settimana", value: "week" },
                  { label: "Su misura", value: "custom" },
                ],
              },
              {
                type: "object",
                name: "stages",
                label: "Programma giornaliero",
                list: true,
                ui: { itemProps: (item) => ({ label: item?.title || "Tappa" }) },
                fields: [
                  { type: "string", name: "title", label: "Titolo", required: true },
                  {
                    type: "string",
                    name: "description",
                    label: "Descrizione",
                    ui: { component: "textarea" },
                    required: true,
                  },
                  { type: "image", name: "image", label: "Foto" },
                  { type: "string", name: "imageAlt", label: "Testo alternativo foto" },
                ],
              },
            ],
          },
        ],
      },
      {
        name: "eventCatalog",
        label: "Eventi e partenze",
        path: "content/events",
        format: "json",
        match: { include: "index" },
        ui: singletonUi("/eventi"),
        fields: [
          {
            type: "object",
            name: "events",
            label: "Eventi",
            list: true,
            ui: { itemProps: (item) => ({ label: item?.name || "Evento" }) },
            fields: [
              { type: "string", name: "name", label: "Nome", required: true, isTitle: true },
              {
                type: "string",
                name: "type",
                label: "Tipo",
                options: ["Maxienduro", "Enduro", "Quad", "4x4", "E-Bike", "Su Misura"],
                required: true,
              },
              { type: "string", name: "duration", label: "Durata", required: true },
              { type: "string", name: "distance", label: "Distanza", required: true },
              { type: "string", name: "level", label: "Livello", required: true },
              { type: "string", name: "offroad", label: "Sterrato", required: true },
              { type: "string", name: "interest", label: "Punti di interesse", required: true },
              { type: "boolean", name: "lunchIncluded", label: "Pranzo incluso" },
              { type: "string", name: "accommodation", label: "Pernottamento / soggiorno" },
              { type: "string", name: "period", label: "Periodo visualizzato", required: true },
              { type: "datetime", name: "startDate", label: "Data di inizio", required: true },
              { type: "datetime", name: "endDate", label: "Data di fine" },
              { type: "string", name: "price", label: "Prezzo" },
              {
                type: "string",
                name: "description",
                label: "Descrizione",
                ui: { component: "textarea" },
                required: true,
              },
              {
                type: "string",
                name: "programNote",
                label: "Nota sul programma",
                ui: { component: "textarea" },
              },
              { type: "string", name: "included", label: "Cosa comprende", list: true },
              { type: "string", name: "equipment", label: "Equipaggiamento", list: true },
              {
                type: "object",
                name: "stages",
                label: "Programma giornaliero",
                list: true,
                ui: { itemProps: (item) => ({ label: item?.title || "Tappa" }) },
                fields: [
                  { type: "string", name: "title", label: "Titolo", required: true },
                  {
                    type: "string",
                    name: "description",
                    label: "Descrizione",
                    ui: { component: "textarea" },
                    required: true,
                  },
                  { type: "image", name: "image", label: "Foto" },
                  { type: "string", name: "imageAlt", label: "Testo alternativo foto" },
                ],
              },
              { type: "string", name: "sourceUrl", label: "Fonte / pagina di riferimento" },
            ],
          },
        ],
      },
      {
        name: "siteSettings",
        label: "Contatti e impostazioni",
        path: "content/settings",
        format: "json",
        match: { include: "index" },
        ui: singletonUi("/?tinaDocument=siteSettings"),
        fields: [
          { type: "string", name: "name", label: "Nome attività", required: true },
          { type: "string", name: "tagline", label: "Tagline", required: true },
          { type: "string", name: "email", label: "Email", required: true },
          { type: "string", name: "phoneE164", label: "Telefono internazionale (solo cifre)", required: true },
          { type: "string", name: "phoneDisplay", label: "Telefono visualizzato", required: true },
          { type: "string", name: "whatsappMessage", label: "Messaggio WhatsApp precompilato", ui: { component: "textarea" } },
          { type: "boolean", name: "contactsVerified", label: "Mostra i contatti pubblici" },
          { type: "string", name: "instagram", label: "URL Instagram" },
          { type: "string", name: "facebook", label: "URL Facebook" },
          { type: "string", name: "socialHandle", label: "Nome social visualizzato" },
          { type: "string", name: "region", label: "Luogo visualizzato" },
          { type: "string", name: "mapsUrl", label: "URL mappa" },
          {
            type: "object",
            name: "cta",
            label: "Pulsanti",
            fields: [
              { type: "string", name: "primary", label: "Pulsante principale", required: true },
              { type: "string", name: "whatsapp", label: "Pulsante WhatsApp", required: true },
            ],
          },
          {
            type: "object",
            name: "tourGroup",
            label: "Dimensione dei gruppi",
            fields: [
              { type: "string", name: "label", label: "Etichetta breve", required: true },
              { type: "string", name: "sentence", label: "Frase completa", required: true },
            ],
          },
          {
            type: "object",
            name: "legal",
            label: "Dati legali",
            fields: [
              { type: "string", name: "businessName", label: "Ragione sociale", required: true },
              { type: "string", name: "legalForm", label: "Forma giuridica", required: true },
              { type: "string", name: "vatNumber", label: "Partita IVA", required: true },
              { type: "string", name: "address", label: "Sede", required: true },
            ],
          },
        ],
      },
    ],
  },
});
